"""remove demo

Revision ID: 01b947c2564e
Revises: 98d072d581ff
Create Date: 2022-08-18 16:17:09.910007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b947c2564e'
down_revision = '98d072d581ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'demo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('demo', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
