"""Created sub task model

Revision ID: 1bcbd8cbc040
Revises: c85e6db96c3b
Create Date: 2022-08-16 15:53:55.979413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bcbd8cbc040'
down_revision = 'c85e6db96c3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_tasks_id'), 'sub_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_sub_tasks_title'), 'sub_tasks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_tasks_title'), table_name='sub_tasks')
    op.drop_index(op.f('ix_sub_tasks_id'), table_name='sub_tasks')
    op.drop_table('sub_tasks')
    # ### end Alembic commands ###
