"""added one fields starrred in Tasks and Subtask model

Revision ID: 5d1c90c2cb42
Revises: 1bcbd8cbc040
Create Date: 2022-08-18 14:25:17.007125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1c90c2cb42'
down_revision = '1bcbd8cbc040'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_tasks', sa.Column('starred', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('starred', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'starred')
    op.drop_column('sub_tasks', 'starred')
    # ### end Alembic commands ###
