"""demo

Revision ID: 98d072d581ff
Revises: ebfe7feb4ec8
Create Date: 2022-08-18 16:15:37.079063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d072d581ff'
down_revision = 'ebfe7feb4ec8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('demo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'demo')
    # ### end Alembic commands ###
