"""Testing migration

Revision ID: c057ee7d0abb
Revises: c37d68c6c850
Create Date: 2023-05-23 13:02:44.211969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c057ee7d0abb'
down_revision = 'c37d68c6c850'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
