"""made some changes in Cascade

Revision ID: c37d68c6c850
Revises: 01b947c2564e
Create Date: 2022-08-22 19:06:39.344809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c37d68c6c850'
down_revision = '01b947c2564e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sub_tasks_task_id_fkey', 'sub_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'sub_tasks', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('task_lists_user_id_fkey', 'task_lists', type_='foreignkey')
    op.create_foreign_key(None, 'task_lists', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tasks_list_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'task_lists', ['list_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_list_id_fkey', 'tasks', 'task_lists', ['list_id'], ['id'])
    op.drop_constraint(None, 'task_lists', type_='foreignkey')
    op.create_foreign_key('task_lists_user_id_fkey', 'task_lists', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'sub_tasks', type_='foreignkey')
    op.create_foreign_key('sub_tasks_task_id_fkey', 'sub_tasks', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
