"""Created sub task model

Revision ID: c85e6db96c3b
Revises: 7b1bdb3231ca
Create Date: 2022-08-16 15:52:03.218636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85e6db96c3b'
down_revision = '7b1bdb3231ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
