"""made some changes in starrred fields of Tasks and Subtask model

Revision ID: ebfe7feb4ec8
Revises: 5d1c90c2cb42
Create Date: 2022-08-18 16:13:53.889945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebfe7feb4ec8'
down_revision = '5d1c90c2cb42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
